version: "3"
services:
  webclient:
    container_name: webclient
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    volumes:
      - ./src:/usr/src/service
    working_dir: /usr/src/service/src
    ports:
      - "3000:3000"
    command: >
      sh -c "tail -f /dev/null"
